### ISSUE TITLE
Plugin does not support ACME v2

### ISSUE THREAD

**Issue by khalid10830** [creactiviti/spring-boot-starter-acme#3]
When I tried to run the command below:
`java -Dserver.port=80 -Dacme.enabled=true -Dacme.domain-name=localhost -Dacme.accept-terms-of-service=true -jar myapplication.jar`

I got this error:

`Caused by: org.shredzone.acme4j.exception.AcmeUnauthorizedException: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.
        at org.shredzone.acme4j.connector.DefaultConnection.createAcmeException(DefaultConnection.java:397)
        at org.shredzone.acme4j.connector.DefaultConnection.accept(DefaultConnection.java:207)
        at org.shredzone.acme4j.RegistrationBuilder.create(RegistrationBuilder.java:88)
        at com.creactiviti.spring.boot.starter.acme.CertGenerator.getOrCreateAccount(CertGenerator.java:158)
        at com.creactiviti.spring.boot.starter.acme.CertGenerator.generate(CertGenerator.java:72)
        at com.creactiviti.spring.boot.starter.acme.AcmeEncryptRunner.run(AcmeEncryptRunner.java:40)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
        ... 13 common frames omitted`

**Comment by RuyXingubit** [comment]
Dear, I believe that in "localhost" it will not work, for the ACME challenge to work, you have to find the machine on the world network, for that, a public IP is needed, and a correct DNS authoritative note, example
site1.domain.com.br,
site1 IN 200.x.x.x
              2804::x

after
java -Dserver.port=80 -Dacme.enabled=true -Dacme.domain-name=site1.domain.com.br -Dacme.accept-terms-of-service=true -jar myapplication.jar
